In [1]:
# Read the data frame
import pandas as pd
messages = pd.read_csv('D:/Projects/NLP/spamhamclassifier.csv', sep=',', names=['label', 'message','host','guest','affrid'], encoding='ISO-8859-1')

In [2]:
messages

label                                            message host guest  \
0       v1                                                 v2  NaN   NaN   
1      ham  Go until jurong point, crazy.. Available only ...  NaN   NaN   
2      ham                      Ok lar... Joking wif u oni...  NaN   NaN   
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...  NaN   NaN   
4      ham  U dun say so early hor... U c already then say...  NaN   NaN   
...    ...                                                ...  ...   ...   
5568  spam  This is the 2nd time we have tried 2 contact u...  NaN   NaN   
5569   ham              Will Ì_ b going to esplanade fr home?  NaN   NaN   
5570   ham  Pity, * was in mood for that. So...any other s...  NaN   NaN   
5571   ham  The guy did some bitching but I acted like i'd...  NaN   NaN   
5572   ham                         Rofl. Its true to its name  NaN   NaN   

     affrid  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       NaN  
...     ...  
5568    NaN  
5569    NaN  
5570    NaN  
5571    NaN  
5572    NaN  

[5573 rows x 5 columns]

In [3]:
type(messages)

pandas.core.frame.DataFrame

In [4]:
messages=messages.iloc[:,0:2]

In [5]:
messages

label                                            message
0       v1                                                 v2
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5573 rows x 2 columns]

In [6]:
# Remove the 0th row
messages = messages.drop(0)

# Reset the index
messages.reset_index(drop=True, inplace=True)


In [7]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
# Data cleaning and preprocessing 
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\satya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [10]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [11]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [12]:
messages.shape

(5572, 2)

In [13]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [14]:
# Train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20,random_state=42)

In [18]:
# Create TF-IDF and NGrams
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=2500, ngram_range=(1, 2))


In [19]:
X_train=tfidf.fit_transform(X_train).toarray()
X_test=tfidf.transform(X_test).toarray()


In [20]:
tfidf.vocabulary_

{'never': 1415,
 'nothing': 1449,
 'forwarded': 726,
 'hi': 924,
 'sm': 1905,
 'alert': 47,
 'message': 1295,
 'match': 1260,
 'please': 1582,
 'call': 248,
 'back': 136,
 'match please': 1261,
 'please call': 1583,
 'call back': 249,
 'bill': 176,
 'letter': 1145,
 'expecting': 650,
 'one': 1487,
 'orange': 1503,
 'may': 1272,
 'still': 1982,
 'say': 1793,
 'hey': 920,
 'darlin': 476,
 'pick': 1560,
 'college': 381,
 'tell': 2070,
 'wen': 2383,
 'love': 1209,
 'pete': 1550,
 'xx': 2471,
 'got': 844,
 'person': 1548,
 'story': 1999,
 'person story': 1549,
 'mom': 1348,
 'check': 331,
 'yo': 2495,
 'half': 888,
 'naked': 1391,
 'take': 2047,
 'role': 1756,
 'rock': 1754,
 'asked': 109,
 'mobile': 1334,
 'free': 731,
 'min': 1303,
 'india': 1006,
 'cust': 461,
 'sed': 1812,
 'yes': 2485,
 'er': 623,
 'dont': 553,
 'giv': 799,
 'shit': 1857,
 'due': 576,
 'day': 484,
 'want': 2333,
 'new': 1416,
 'nokia': 1435,
 'colour': 382,
 'phone': 1552,
 'minute': 1312,
 'text': 2084,
 'camcorder': 

In [ ]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "%.3g"%x))

In [24]:
print("X_train:\n", X_train)

X_train:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0.348 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.399 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [25]:
print("X_test:\n", X_test)

X_test:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [26]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model=MultinomialNB().fit(X_train,y_train)

In [27]:
spam_tfidf_model

MultinomialNB()

In [28]:
y_pred=spam_tfidf_model.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Tfidf Model accuracy: ",accuracy_score(y_test,y_pred))


Tfidf Model accuracy:  0.9775784753363229


In [31]:
print("Tfidf Model classification_report: ",classification_report(y_test,y_pred))

Tfidf Model classification_report:                precision    recall  f1-score   support

           0       0.99      0.84      0.91       149
           1       0.98      1.00      0.99       966

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [32]:
print("Tfidf confusion matrix: ",confusion_matrix(y_test,y_pred))

Tfidf confusion matrix:  [[125  24]
 [  1 965]]
