In [85]:
# Read the data frame
import pandas as pd
messages = pd.read_csv('D:/Projects/NLP/SpamHamClassification/spamhamclassifier.csv', sep=',', names=['label', 'message','host','guest','affrid'], encoding='ISO-8859-1')

In [86]:
messages

label                                            message host guest  \
0       v1                                                 v2  NaN   NaN   
1      ham  Go until jurong point, crazy.. Available only ...  NaN   NaN   
2      ham                      Ok lar... Joking wif u oni...  NaN   NaN   
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...  NaN   NaN   
4      ham  U dun say so early hor... U c already then say...  NaN   NaN   
...    ...                                                ...  ...   ...   
5568  spam  This is the 2nd time we have tried 2 contact u...  NaN   NaN   
5569   ham              Will Ì_ b going to esplanade fr home?  NaN   NaN   
5570   ham  Pity, * was in mood for that. So...any other s...  NaN   NaN   
5571   ham  The guy did some bitching but I acted like i'd...  NaN   NaN   
5572   ham                         Rofl. Its true to its name  NaN   NaN   

     affrid  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       NaN  
...     ...  
5568    NaN  
5569    NaN  
5570    NaN  
5571    NaN  
5572    NaN  

[5573 rows x 5 columns]

In [87]:
type(messages)

pandas.core.frame.DataFrame

In [88]:
messages=messages.iloc[:,0:2]

In [89]:
messages

label                                            message
0       v1                                                 v2
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5573 rows x 2 columns]

In [90]:
# Remove the 0th row
messages = messages.drop(0)

# Reset the index
messages.reset_index(drop=True, inplace=True)


In [91]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [92]:
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [93]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

In [94]:
vec_king.shape

(300,)

In [95]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [96]:
# Data cleaning and preprocessing 
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\satya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [97]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
snowballstemmer=SnowballStemmer('english')

In [98]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[snowballstemmer.stem(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [99]:
corpus

['go until jurong point crazi avail onli in bugi n great world la e buffet cine there got amor wat',
 'ok lar joke wif u oni',
 'free entri in a wkli comp to win fa cup final tkts st may text fa to to receiv entri question std txt rate t c s appli over s',
 'u dun say so earli hor u c alreadi then say',
 'nah i don t think he goe to usf he live around here though',
 'freemsg hey there darl it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'as per your request mell mell oru minnaminungint nurungu vettam has been set as your callertun for all caller press to copi your friend callertun',
 'winner as a valu network custom you have been select to receivea prize reward to claim call claim code kl valid hour onli',
 'had your mobil month or more u r entitl to updat to the latest colour mobil with camera for free call the mobil updat co free on',
 'i m g

In [100]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [101]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))
    

In [102]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazi',
  'avail',
  'onli',
  'in',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'in',
  'wkli',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli',
  'over'],
 ['dun', 'say', 'so', 'earli', 'hor', 'alreadi', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'goe',
  'to',
  'usf',
  'he',
  'live',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darl',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with

In [103]:
# Let's train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [104]:
# TO get all the vocabulary
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'your',
 'for',
 'call',
 'that',
 'of',
 'have',
 'on',
 'now',
 'do',
 'are',
 'can',
 'so',
 'go',
 'get',
 'but',
 'not',
 'be',
 'or',
 'we',
 'at',
 'will',
 'if',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'how',
 'gt',
 'lt',
 'up',
 'what',
 'come',
 'when',
 'ok',
 'day',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'love',
 'like',
 'time',
 'want',
 'good',
 'then',
 'am',
 'got',
 'there',
 'text',
 'was',
 'he',
 'onli',
 'send',
 'need',
 'txt',
 'one',
 'today',
 'as',
 'by',
 'take',
 'see',
 'stop',
 'don',
 'home',
 'about',
 'think',
 'she',
 'week',
 'repli',
 'lor',
 'sorri',
 'tell',
 'still',
 'mobil',
 'back',
 'da',
 'our',
 'make',
 'dont',
 'phone',
 'say',
 'pleas',
 'hi',
 'new',
 'they',
 'work',
 'later',
 'pls',
 'her',
 'ani',
 'hope',
 'ask',
 'did',
 'miss',
 'been',
 'min',
 'dear',
 'meet',
 'some',
 'an',
 'messag',
 'here',
 'night',
 'wait',
 'happi',
 'well',
 'who',
 'wher

In [105]:
model.corpus_count

5569

In [106]:
model.epochs

5

In [107]:
model.wv.similar_by_word('good')

[('love', 0.9984375238418579),
 ('hope', 0.9983986020088196),
 ('where', 0.9982076287269592),
 ('about', 0.9981935620307922),
 ('well', 0.9980875253677368),
 ('did', 0.9980707764625549),
 ('got', 0.9980477094650269),
 ('goe', 0.9980066418647766),
 ('was', 0.997991144657135),
 ('night', 0.9979244470596313)]

In [108]:
model.wv['good']

array([-2.32596055e-01,  3.61320645e-01,  1.42443106e-01,  1.28977284e-01,
        4.77061458e-02, -7.10191369e-01,  2.09787384e-01,  8.82695794e-01,
       -3.75064820e-01, -3.70984912e-01, -1.07201718e-01, -6.10186279e-01,
       -1.12934291e-01,  9.22043528e-03,  1.34869605e-01, -2.22798347e-01,
        6.82967156e-02, -2.87495464e-01, -1.43175181e-02, -7.54010260e-01,
        2.27929384e-01,  1.03435904e-01,  2.31236413e-01, -1.74113572e-01,
       -1.22460961e-01,  1.98609568e-02, -2.66419411e-01, -2.01516226e-01,
       -2.77374655e-01, -1.42412763e-02,  3.76735389e-01,  3.46875340e-02,
        3.02512795e-01, -2.59083539e-01,  7.23821856e-03,  3.97423297e-01,
        1.80026650e-01, -2.84362137e-01, -1.57928467e-01, -6.08063638e-01,
       -8.91202968e-03, -3.15199137e-01, -4.78827618e-02,  6.44960701e-02,
        2.82104015e-01, -1.58423007e-01, -2.77669609e-01, -1.22401319e-01,
        1.21102966e-01,  2.60026693e-01,  5.37973680e-02, -4.06727016e-01,
       -1.06156528e-01, -

In [109]:
import numpy as np
from tqdm import tqdm

def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if vectors:  # Check if the list is not empty
        return np.mean(vectors, axis=0)  # Average for each sentence
    else:
        return np.zeros(model.vector_size)  # Return a zero vector for empty inputs


In [110]:

X = []  # Initialize an empty list to store sentence embeddings
for i in tqdm(range(len(words))):  # Use tqdm to show progress
    X.append(avg_word2vec(words[i]))  # Append the embedding for each sentence

100%|██████████| 5569/5569 [00:01<00:00, 5110.54it/s]


In [111]:
X

[array([-0.16676459,  0.26009715,  0.09354336,  0.10920542,  0.03028329,
        -0.5049154 ,  0.11399272,  0.6454645 , -0.2541919 , -0.26365373,
        -0.08331849, -0.4234233 , -0.06496694,  0.01859309,  0.10152979,
        -0.16637355,  0.04337392, -0.23865238,  0.00503523, -0.56369436,
         0.159795  ,  0.08720891,  0.14286835, -0.10804641, -0.10411386,
        -0.0034111 , -0.17974113, -0.11927447, -0.19431876,  0.00401754,
         0.30744493,  0.00665679,  0.20891902, -0.17565751, -0.01340591,
         0.306118  ,  0.13394117, -0.23511575, -0.14064623, -0.4331117 ,
        -0.01179006, -0.24492545, -0.06620981,  0.04080079,  0.19965182,
        -0.08788653, -0.20983434, -0.08140653,  0.06848709,  0.17994557,
         0.06762539, -0.29140845, -0.09882663, -0.06311848, -0.11380553,
         0.19836546,  0.16806582, -0.08109136, -0.2955702 ,  0.18257293,
         0.12912361,  0.0074443 , -0.02166254,  0.01094801, -0.27823976,
         0.2653121 ,  0.20122056,  0.19483854, -0.3

In [112]:
len(X)

5569

In [113]:
# Independent features
X_new=np.array(X)

In [114]:
X_new.shape

(5569, 100)

In [115]:
X_new[0].shape

(100,)

In [116]:
X_new[0]

array([-0.16676459,  0.26009715,  0.09354336,  0.10920542,  0.03028329,
       -0.50491542,  0.11399272,  0.64546448, -0.25419191, -0.26365373,
       -0.08331849, -0.42342329, -0.06496694,  0.01859309,  0.10152979,
       -0.16637355,  0.04337392, -0.23865238,  0.00503523, -0.56369436,
        0.159795  ,  0.08720891,  0.14286835, -0.10804641, -0.10411386,
       -0.0034111 , -0.17974113, -0.11927447, -0.19431876,  0.00401754,
        0.30744493,  0.00665679,  0.20891902, -0.17565751, -0.01340591,
        0.30611801,  0.13394117, -0.23511575, -0.14064623, -0.4331117 ,
       -0.01179006, -0.24492545, -0.06620981,  0.04080079,  0.19965182,
       -0.08788653, -0.20983434, -0.08140653,  0.06848709,  0.17994557,
        0.06762539, -0.29140845, -0.09882663, -0.06311848, -0.11380553,
        0.19836546,  0.16806582, -0.08109136, -0.29557019,  0.18257293,
        0.12912361,  0.0074443 , -0.02166254,  0.01094801, -0.27823976,
        0.26531211,  0.20122056,  0.19483854, -0.35240108,  0.34

In [117]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [118]:
messages.shape

(5572, 2)

In [119]:
X_new.shape

(5569, 100)

In [120]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [121]:
y=messages[list(map(lambda X: len(X)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [122]:
y.shape

(5569,)

In [123]:
len(X)

5569

In [124]:
X[0].reshape(1,-1).shape

(1, 100)

In [125]:
X[1]

array([-0.15980446,  0.24539022,  0.08485804,  0.09736396,  0.03546269,
       -0.4874961 ,  0.12005018,  0.6218128 , -0.22907837, -0.25371146,
       -0.07714638, -0.40270972, -0.06973901,  0.02834746,  0.08753043,
       -0.15392005,  0.04334477, -0.22563976, -0.00539818, -0.5398638 ,
        0.15501438,  0.08036336,  0.12102513, -0.10508522, -0.10135968,
        0.00394497, -0.17249806, -0.11712512, -0.18197948,  0.0015296 ,
        0.27991697,  0.00446539,  0.20480597, -0.17183621, -0.01686121,
        0.28116408,  0.13099428, -0.2263378 , -0.13452421, -0.41601193,
       -0.01512418, -0.22542313, -0.06181871,  0.04310441,  0.18809825,
       -0.09146646, -0.19802037, -0.07267012,  0.06293041,  0.16447319,
        0.06543006, -0.2784016 , -0.08778066, -0.06399781, -0.10339006,
        0.18926075,  0.16648096, -0.0813849 , -0.27564004,  0.1778933 ,
        0.1165585 , -0.00279456, -0.01213778,  0.01160522, -0.27067474,
        0.2512114 ,  0.184636  ,  0.19054517, -0.32216594,  0.33

In [126]:
df=pd.DataFrame()
for i in range(0,len(X)):
    df=df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)

C:\Users\satya\AppData\Local\Temp\ipykernel_11796\3473899133.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)


In [127]:
df.shape

(5569, 100)

In [128]:
df.head()

0         1         2         3         4         5         6   \
0 -0.166765  0.260097  0.093543  0.109205  0.030283 -0.504915  0.113993   
1 -0.159804  0.245390  0.084858  0.097364  0.035463 -0.487496  0.120050   
2 -0.165172  0.299825  0.081503  0.153100  0.030906 -0.541047  0.040412   
3 -0.222469  0.341749  0.129077  0.129019  0.049912 -0.687250  0.187030   
4 -0.174017  0.274453  0.101791  0.110108  0.040904 -0.552264  0.132903   

         7         8         9   ...        90        91        92        93  \
0  0.645464 -0.254192 -0.263654  ...  0.329338  0.094547  0.073309  0.120174   
1  0.621813 -0.229078 -0.253711  ...  0.317559  0.087657  0.080074  0.116629   
2  0.683303 -0.273015 -0.273230  ...  0.359027  0.095422  0.032205  0.142777   
3  0.868969 -0.326398 -0.349142  ...  0.449210  0.128896  0.129604  0.155610   
4  0.689226 -0.258510 -0.277012  ...  0.353627  0.090741  0.097653  0.118809   

         94        95        96        97        98        99  
0  0.467786  0.308428  0.186996 -0.234949  0.119217 -0.058839  
1  0.449182  0.295339  0.176235 -0.220735  0.121941 -0.049910  
2  0.449094  0.287930  0.200286 -0.270667  0.134368 -0.085893  
3  0.648742  0.428026  0.246632 -0.300777  0.161424 -0.069853  
4  0.505187  0.339849  0.196714 -0.240798  0.122588 -0.054982  

[5 rows x 100 columns]

In [129]:
# Independent features
X=df

In [130]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [131]:
# Train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [132]:
X_train.head()

0         1         2         3         4         5         6   \
3918 -0.187885  0.288064  0.109091  0.109366  0.037518 -0.578746  0.150620   
3986 -0.197419  0.315490  0.110993  0.135133  0.039909 -0.612212  0.132336   
2758 -0.162455  0.268076  0.095236  0.109866  0.034216 -0.521721  0.118272   
4796 -0.218975  0.364076  0.128568  0.153044  0.046953 -0.729108  0.158945   
4503 -0.193666  0.327723  0.118804  0.109850  0.056156 -0.679354  0.200556   

            7         8         9   ...        90        91        92  \
3918  0.726870 -0.276778 -0.293828  ...  0.372057  0.102019  0.105347   
3986  0.777099 -0.299069 -0.312044  ...  0.401930  0.111622  0.091518   
2758  0.656453 -0.253843 -0.265032  ...  0.344467  0.093482  0.085279   
4796  0.906154 -0.346436 -0.368841  ...  0.471755  0.118499  0.111286   
4503  0.829825 -0.309089 -0.328466  ...  0.438353  0.096347  0.162377   

            93        94        95        96        97        98        99  
3918  0.122461  0.546158  0.367286  0.204323 -0.248356  0.127907 -0.056782  
3986  0.144305  0.556826  0.366141  0.223284 -0.279374  0.148170 -0.070936  
2758  0.119707  0.475914  0.315774  0.188057 -0.232704  0.119907 -0.058364  
4796  0.163092  0.659422  0.435613  0.256210 -0.318269  0.165930 -0.088235  
4503  0.130692  0.640118  0.427776  0.215875 -0.264809  0.145678 -0.063755  

[5 rows x 100 columns]

In [133]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [134]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [135]:
y_pred=classifier.predict(X_test)

In [136]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print("AVG word2vec: ",accuracy_score(y_test,y_pred))

AVG word2vec:  0.9694793536804309


In [137]:
print("AVG word2vec confusion matrix: ",confusion_matrix(y_test,y_pred))

AVG word2vec confusion matrix:  [[138  23]
 [ 11 942]]


In [138]:
print("AVG word2vec classification report: ",classification_report(y_test,y_pred))

AVG word2vec classification report:                precision    recall  f1-score   support

           0       0.93      0.86      0.89       161
           1       0.98      0.99      0.98       953

    accuracy                           0.97      1114
   macro avg       0.95      0.92      0.94      1114
weighted avg       0.97      0.97      0.97      1114

